name: Python Default CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  PYTHON_VERSION: '3.13.2'

jobs:
  codeqa:
    uses: nicburgt/.github/.github/workflows/codeqa.yml@cea79ef34e69a346abe36f79f14c45fc706d8d18
    with:
      python-version: $PYTHON_VERSION
  tests:
    uses: nicburgt/.github/.github/workflows/tests.yml@cea79ef34e69a346abe36f79f14c45fc706d8d18
    with:
      python-version: $PYTHON_VERSION
      test-results-artifact-name: 'coverage-results'