name: Python Default CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  python_version: 3.13

jobs:
  # Silly workaround due to env limitations with reusable workflows.
  # See: https://github.com/orgs/community/discussions/26671
  envvars:
    runs-on: ubuntu-22.04
    outputs:
      python_version: ${{ env.python_version }}
    steps:
      - run: echo "exposing environment variables as outputs"
  codeqa:
    needs: envvars
    uses: nicburgt/.github/.github/workflows/codeqa.yml@cea79ef34e69a346abe36f79f14c45fc706d8d18
    with:
      python-version: ${{ needs.envvars.outputs.python_version }}
  tests:
    needs: envvars
    uses: nicburgt/.github/.github/workflows/tests.yml@cea79ef34e69a346abe36f79f14c45fc706d8d18
    with:
      python-version: ${{ needs.envvars.outputs.python_version }}
      test-results-artifact-name: 'coverage-results'